### ISSUE TITLE
Destacar melhor o resultado do quiz 

### ISSUE THREAD

**Issue by rafaelcorsi** [insper-education/active-handout-theme#2]
Eu achei confuso a forma como o quiz exibe o resultado errado/certo quando temos apenas dois itens e o aluno clicou no errado.

@toshikurauchi  o que acha?

![image](https://user-images.githubusercontent.com/1039615/153692129-6cae44de-885e-40d4-b75b-5f8eef841c6a.png)

**Comment by toshikurauchi** [comment]
@rafaelcorsi realmente está confuso. Mesmo com várias opções eu acho que ainda não está muito claro. Alguma sugestão de como fazer?
